package mocks

import context "context"
import dep_radar "github.com/stamm/dep_radar"
import mock "github.com/stretchr/testify/mock"

// IApp is an autogenerated mock type for the IApp type
type IApp struct {
	mock.Mock
}

// Branch provides a mock function with given fields:
func (_m *IApp) Branch() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Deps provides a mock function with given fields: _a0
func (_m *IApp) Deps(_a0 context.Context) (dep_radar.AppDeps, error) {
	ret := _m.Called(_a0)

	var r0 dep_radar.AppDeps
	if rf, ok := ret.Get(0).(func(context.Context) dep_radar.AppDeps); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(dep_radar.AppDeps)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Package provides a mock function with given fields:
func (_m *IApp) Package() dep_radar.Pkg {
	ret := _m.Called()

	var r0 dep_radar.Pkg
	if rf, ok := ret.Get(0).(func() dep_radar.Pkg); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(dep_radar.Pkg)
	}

	return r0
}

// Provider provides a mock function with given fields:
func (_m *IApp) Provider() dep_radar.IProvider {
	ret := _m.Called()

	var r0 dep_radar.IProvider
	if rf, ok := ret.Get(0).(func() dep_radar.IProvider); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(dep_radar.IProvider)
		}
	}

	return r0
}

var _ dep_radar.IApp = (*IApp)(nil)
