package mocks

import context "context"
import dep_radar "github.com/stamm/dep_radar"
import mock "github.com/stretchr/testify/mock"

// IDepTool is an autogenerated mock type for the IDepTool type
type IDepTool struct {
	mock.Mock
}

// Deps provides a mock function with given fields: _a0, _a1
func (_m *IDepTool) Deps(_a0 context.Context, _a1 dep_radar.IApp) (dep_radar.AppDeps, error) {
	ret := _m.Called(_a0, _a1)

	var r0 dep_radar.AppDeps
	if rf, ok := ret.Get(0).(func(context.Context, dep_radar.IApp) dep_radar.AppDeps); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(dep_radar.AppDeps)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, dep_radar.IApp) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Name provides a mock function with given fields:
func (_m *IDepTool) Name() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

var _ dep_radar.IDepTool = (*IDepTool)(nil)
