package mocks

import interfaces "github.com/stamm/dep_radar/interfaces"
import mock "github.com/stretchr/testify/mock"

// IApp is an autogenerated mock type for the IApp type
type IApp struct {
	mock.Mock
}

// File provides a mock function with given fields: filename
func (_m *IApp) File(filename string) ([]byte, error) {
	ret := _m.Called(filename)

	var r0 []byte
	if rf, ok := ret.Get(0).(func(string) []byte); ok {
		r0 = rf(filename)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(filename)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Package provides a mock function with given fields:
func (_m *IApp) Package() interfaces.Pkg {
	ret := _m.Called()

	var r0 interfaces.Pkg
	if rf, ok := ret.Get(0).(func() interfaces.Pkg); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(interfaces.Pkg)
	}

	return r0
}

var _ interfaces.IApp = (*IApp)(nil)
