package mocks

import interfaces "github.com/stamm/dep_radar/interfaces"
import mock "github.com/stretchr/testify/mock"

// IReposGetter is an autogenerated mock type for the IReposGetter type
type IReposGetter struct {
	mock.Mock
}

// Apps provides a mock function with given fields:
func (_m *IReposGetter) Apps() ([]interfaces.Pkg, error) {
	ret := _m.Called()

	var r0 []interfaces.Pkg
	if rf, ok := ret.Get(0).(func() []interfaces.Pkg); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]interfaces.Pkg)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

var _ interfaces.IReposGetter = (*IReposGetter)(nil)
