package mocks

import interfaces "github.com/stamm/dep_radar/interfaces"
import mock "github.com/stretchr/testify/mock"

// IReposGetter is an autogenerated mock type for the IReposGetter type
type IReposGetter struct {
	mock.Mock
}

// Apps provides a mock function with given fields:
func (_m *IReposGetter) Apps() []interfaces.IApp {
	ret := _m.Called()

	var r0 []interfaces.IApp
	if rf, ok := ret.Get(0).(func() []interfaces.IApp); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]interfaces.IApp)
		}
	}

	return r0
}

var _ interfaces.IReposGetter = (*IReposGetter)(nil)
